<?php

namespace Tests\Feature\Seo;

use App\Models\Tour;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TourLocalizedSeoTest extends TestCase
{
    use RefreshDatabase;

    private function tour(array $overrides = []): Tour
    {
        return Tour::factory()->create(array_merge([
            'is_published' => true,
        ], $overrides));
    }

    /** @test */
    public function it_resolves_a_tour_by_its_translated_english_slug(): void
    {
        $tour = $this->tour([
            'slug' => 'laguna-humantay',
            'slug_en' => 'humantay-lake',
        ]);

        $response = $this->get('/en/tours/detalle/humantay-lake');

        $response->assertOk();
        $response->assertSee($tour->title_en ?: $tour->title_es);
    }

    /** @test */
    public function it_falls_back_to_the_spanish_slug_when_the_translated_slug_is_empty(): void
    {
        $tour = $this->tour([
            'slug' => 'city-tour-lima',
            'slug_en' => null,
        ]);

        // No slug_en configured yet — the English page must still resolve
        // through the Spanish slug instead of 404-ing.
        $response = $this->get('/en/tours/detalle/city-tour-lima');

        $response->assertOk();
    }

    /** @test */
    public function it_redirects_301_from_the_spanish_slug_to_the_translated_slug_under_a_non_spanish_locale(): void
    {
        $this->tour([
            'slug' => 'laguna-humantay',
            'slug_en' => 'humantay-lake',
        ]);

        $response = $this->get('/en/tours/detalle/laguna-humantay');

        $response->assertRedirect('/en/tours/detalle/humantay-lake');
        $response->assertStatus(301);
    }

    /** @test */
    public function it_does_not_redirect_when_there_is_no_translated_slug(): void
    {
        $this->tour([
            'slug' => 'city-tour-lima',
            'slug_en' => null,
        ]);

        // Same slug used under /en/ — since there is no slug_en, this IS the
        // canonical URL for English too. No redirect loop, just 200.
        $response = $this->get('/en/tours/detalle/city-tour-lima');

        $response->assertOk();
    }

    /** @test */
    public function it_returns_404_for_a_slug_that_does_not_exist_in_any_locale(): void
    {
        $response = $this->get('/en/tours/detalle/no-existe-este-tour');

        $response->assertNotFound();
    }

    /** @test */
    public function it_emits_the_three_real_localized_urls_in_hreflang_and_canonical(): void
    {
        $this->tour([
            'slug' => 'laguna-humantay',
            'slug_en' => 'humantay-lake',
            'slug_pt' => 'lagoa-humantay',
        ]);

        $response = $this->get('/es/tours/detalle/laguna-humantay');
        $response->assertOk();

        $response->assertSee('hreflang="es"', false);
        $response->assertSee('http://lima-tour.test/es/tours/detalle/laguna-humantay', false);
        $response->assertSee('http://lima-tour.test/en/tours/detalle/humantay-lake', false);
        $response->assertSee('http://lima-tour.test/pt/tours/detalle/lagoa-humantay', false);
    }

    /** @test */
    public function it_uses_the_meta_title_and_description_from_the_admin_panel_when_present(): void
    {
        $this->tour([
            'slug' => 'city-tour-lima',
            'meta_title_es' => 'Título SEO cargado desde el panel',
            'meta_description_es' => 'Descripción SEO cargada desde el panel de administración.',
        ]);

        $response = $this->get('/es/tours/detalle/city-tour-lima');

        $response->assertOk();
        $response->assertSee('Título SEO cargado desde el panel', false);
        $response->assertSee('Descripción SEO cargada desde el panel de administración.', false);
    }

    /** @test */
    public function custom_jsonld_replaces_the_auto_generated_schema_when_present(): void
    {
        $customJsonLd = json_encode(['@context' => 'https://schema.org', '@type' => 'Product', 'name' => 'JSON-LD manual de prueba']);

        $this->tour([
            'slug' => 'city-tour-lima',
            'schema_jsonld_es' => $customJsonLd,
        ]);

        $response = $this->get('/es/tours/detalle/city-tour-lima');

        $response->assertOk();
        $response->assertSee('JSON-LD manual de prueba', false);
        // The auto-generated block's distinctive key should not be present
        // when the custom JSON-LD replaces it.
        $response->assertDontSee('"touristType"', false);
    }

    /** @test */
    public function meta_title_falls_back_to_the_autogenerated_title_when_no_admin_value_is_set(): void
    {
        $tour = $this->tour([
            'slug' => 'city-tour-lima',
            'title_es' => 'CITY TOUR LIMA',
            'meta_title_es' => null,
        ]);

        $response = $this->get('/es/tours/detalle/city-tour-lima');

        $response->assertOk();
        // No admin meta title configured — falls back to the old behaviour
        // (Title Case of the tour title + site name), never an empty <title>.
        $response->assertSee('City Tour Lima', false);
    }
}
