<?php

/**
 * Prefijos telefónicos internacionales (2026-08-25).
 *
 * El selector del checkout traía 16 países escritos a mano en el Blade, así que
 * un cliente de cualquier otro lado no podía dejar su teléfono. Acá está la
 * lista completa: los 242 territorios con prefijo E.164 asignado.
 *
 * GENERADO — no editar a mano. Los nombres salen de ICU (extensión intl) y se
 * hornearon en el archivo para que el sitio NO dependa de que el hosting la
 * tenga cargada. Para regenerarlo, ver el script del lote de 2026-08-25.
 *
 * Formato: ISO 3166-1 alpha-2 => ['dial' => prefijo sin '+', 'flag' => emoji,
 * 'names' => nombre por idioma]. La bandera se guarda ya resuelta porque
 * construirla con mb_chr() en cada render son 480 llamadas por página.
 *
 * `featured` son los que van arriba del todo, antes de la lista completa: los
 * mercados reales de Lima View Tours según las reservas. Se pueden reordenar
 * sin tocar el resto.
 *
 * Cuando un prefijo lo comparten varios países (+1 en Norteamérica y el Caribe,
 * +7 en Rusia y Kazajistán) cada país aparece con su bandera y su nombre: el
 * valor enviado es el mismo, que es lo único que le importa al teléfono.
 */

return [

    'default' => 'PE',

    'featured' => ['PE', 'US', 'ES', 'MX', 'CL', 'AR', 'CO', 'BR', 'CA', 'GB', 'FR', 'DE', 'IT', 'AU'],

    'countries' => [
        'AF' => ['dial' => '93', 'flag' => '🇦🇫', 'names' => ['es' => 'Afganistán', 'en' => 'Afghanistan', 'pt' => 'Afeganistão']],
        'AL' => ['dial' => '355', 'flag' => '🇦🇱', 'names' => ['es' => 'Albania', 'en' => 'Albania', 'pt' => 'Albânia']],
        'DE' => ['dial' => '49', 'flag' => '🇩🇪', 'names' => ['es' => 'Alemania', 'en' => 'Germany', 'pt' => 'Alemanha']],
        'AD' => ['dial' => '376', 'flag' => '🇦🇩', 'names' => ['es' => 'Andorra', 'en' => 'Andorra', 'pt' => 'Andorra']],
        'AO' => ['dial' => '244', 'flag' => '🇦🇴', 'names' => ['es' => 'Angola', 'en' => 'Angola', 'pt' => 'Angola']],
        'AI' => ['dial' => '1264', 'flag' => '🇦🇮', 'names' => ['es' => 'Anguila', 'en' => 'Anguilla', 'pt' => 'Anguila']],
        'AG' => ['dial' => '1268', 'flag' => '🇦🇬', 'names' => ['es' => 'Antigua y Barbuda', 'en' => 'Antigua & Barbuda', 'pt' => 'Antígua e Barbuda']],
        'SA' => ['dial' => '966', 'flag' => '🇸🇦', 'names' => ['es' => 'Arabia Saudí', 'en' => 'Saudi Arabia', 'pt' => 'Arábia Saudita']],
        'DZ' => ['dial' => '213', 'flag' => '🇩🇿', 'names' => ['es' => 'Argelia', 'en' => 'Algeria', 'pt' => 'Argélia']],
        'AR' => ['dial' => '54', 'flag' => '🇦🇷', 'names' => ['es' => 'Argentina', 'en' => 'Argentina', 'pt' => 'Argentina']],
        'AM' => ['dial' => '374', 'flag' => '🇦🇲', 'names' => ['es' => 'Armenia', 'en' => 'Armenia', 'pt' => 'Armênia']],
        'AW' => ['dial' => '297', 'flag' => '🇦🇼', 'names' => ['es' => 'Aruba', 'en' => 'Aruba', 'pt' => 'Aruba']],
        'AU' => ['dial' => '61', 'flag' => '🇦🇺', 'names' => ['es' => 'Australia', 'en' => 'Australia', 'pt' => 'Austrália']],
        'AT' => ['dial' => '43', 'flag' => '🇦🇹', 'names' => ['es' => 'Austria', 'en' => 'Austria', 'pt' => 'Áustria']],
        'AZ' => ['dial' => '994', 'flag' => '🇦🇿', 'names' => ['es' => 'Azerbaiyán', 'en' => 'Azerbaijan', 'pt' => 'Azerbaijão']],
        'BS' => ['dial' => '1242', 'flag' => '🇧🇸', 'names' => ['es' => 'Bahamas', 'en' => 'Bahamas', 'pt' => 'Bahamas']],
        'BD' => ['dial' => '880', 'flag' => '🇧🇩', 'names' => ['es' => 'Bangladés', 'en' => 'Bangladesh', 'pt' => 'Bangladesh']],
        'BB' => ['dial' => '1246', 'flag' => '🇧🇧', 'names' => ['es' => 'Barbados', 'en' => 'Barbados', 'pt' => 'Barbados']],
        'BH' => ['dial' => '973', 'flag' => '🇧🇭', 'names' => ['es' => 'Baréin', 'en' => 'Bahrain', 'pt' => 'Barein']],
        'BE' => ['dial' => '32', 'flag' => '🇧🇪', 'names' => ['es' => 'Bélgica', 'en' => 'Belgium', 'pt' => 'Bélgica']],
        'BZ' => ['dial' => '501', 'flag' => '🇧🇿', 'names' => ['es' => 'Belice', 'en' => 'Belize', 'pt' => 'Belize']],
        'BJ' => ['dial' => '229', 'flag' => '🇧🇯', 'names' => ['es' => 'Benín', 'en' => 'Benin', 'pt' => 'Benin']],
        'BM' => ['dial' => '1441', 'flag' => '🇧🇲', 'names' => ['es' => 'Bermudas', 'en' => 'Bermuda', 'pt' => 'Bermudas']],
        'BY' => ['dial' => '375', 'flag' => '🇧🇾', 'names' => ['es' => 'Bielorrusia', 'en' => 'Belarus', 'pt' => 'Bielorrússia']],
        'BO' => ['dial' => '591', 'flag' => '🇧🇴', 'names' => ['es' => 'Bolivia', 'en' => 'Bolivia', 'pt' => 'Bolívia']],
        'BA' => ['dial' => '387', 'flag' => '🇧🇦', 'names' => ['es' => 'Bosnia y Herzegovina', 'en' => 'Bosnia & Herzegovina', 'pt' => 'Bósnia e Herzegovina']],
        'BW' => ['dial' => '267', 'flag' => '🇧🇼', 'names' => ['es' => 'Botsuana', 'en' => 'Botswana', 'pt' => 'Botsuana']],
        'BR' => ['dial' => '55', 'flag' => '🇧🇷', 'names' => ['es' => 'Brasil', 'en' => 'Brazil', 'pt' => 'Brasil']],
        'BN' => ['dial' => '673', 'flag' => '🇧🇳', 'names' => ['es' => 'Brunéi', 'en' => 'Brunei', 'pt' => 'Brunei']],
        'BG' => ['dial' => '359', 'flag' => '🇧🇬', 'names' => ['es' => 'Bulgaria', 'en' => 'Bulgaria', 'pt' => 'Bulgária']],
        'BF' => ['dial' => '226', 'flag' => '🇧🇫', 'names' => ['es' => 'Burkina Faso', 'en' => 'Burkina Faso', 'pt' => 'Burquina Faso']],
        'BI' => ['dial' => '257', 'flag' => '🇧🇮', 'names' => ['es' => 'Burundi', 'en' => 'Burundi', 'pt' => 'Burundi']],
        'BT' => ['dial' => '975', 'flag' => '🇧🇹', 'names' => ['es' => 'Bután', 'en' => 'Bhutan', 'pt' => 'Butão']],
        'CV' => ['dial' => '238', 'flag' => '🇨🇻', 'names' => ['es' => 'Cabo Verde', 'en' => 'Cape Verde', 'pt' => 'Cabo Verde']],
        'KH' => ['dial' => '855', 'flag' => '🇰🇭', 'names' => ['es' => 'Camboya', 'en' => 'Cambodia', 'pt' => 'Camboja']],
        'CM' => ['dial' => '237', 'flag' => '🇨🇲', 'names' => ['es' => 'Camerún', 'en' => 'Cameroon', 'pt' => 'Camarões']],
        'CA' => ['dial' => '1', 'flag' => '🇨🇦', 'names' => ['es' => 'Canadá', 'en' => 'Canada', 'pt' => 'Canadá']],
        'BQ' => ['dial' => '599', 'flag' => '🇧🇶', 'names' => ['es' => 'Caribe neerlandés', 'en' => 'Caribbean Netherlands', 'pt' => 'Países Baixos Caribenhos']],
        'QA' => ['dial' => '974', 'flag' => '🇶🇦', 'names' => ['es' => 'Catar', 'en' => 'Qatar', 'pt' => 'Catar']],
        'TD' => ['dial' => '235', 'flag' => '🇹🇩', 'names' => ['es' => 'Chad', 'en' => 'Chad', 'pt' => 'Chade']],
        'CZ' => ['dial' => '420', 'flag' => '🇨🇿', 'names' => ['es' => 'Chequia', 'en' => 'Czechia', 'pt' => 'Tchéquia']],
        'CL' => ['dial' => '56', 'flag' => '🇨🇱', 'names' => ['es' => 'Chile', 'en' => 'Chile', 'pt' => 'Chile']],
        'CN' => ['dial' => '86', 'flag' => '🇨🇳', 'names' => ['es' => 'China', 'en' => 'China', 'pt' => 'China']],
        'CY' => ['dial' => '357', 'flag' => '🇨🇾', 'names' => ['es' => 'Chipre', 'en' => 'Cyprus', 'pt' => 'Chipre']],
        'VA' => ['dial' => '39', 'flag' => '🇻🇦', 'names' => ['es' => 'Ciudad del Vaticano', 'en' => 'Vatican City', 'pt' => 'Cidade do Vaticano']],
        'CO' => ['dial' => '57', 'flag' => '🇨🇴', 'names' => ['es' => 'Colombia', 'en' => 'Colombia', 'pt' => 'Colômbia']],
        'KM' => ['dial' => '269', 'flag' => '🇰🇲', 'names' => ['es' => 'Comoras', 'en' => 'Comoros', 'pt' => 'Comores']],
        'CG' => ['dial' => '242', 'flag' => '🇨🇬', 'names' => ['es' => 'Congo', 'en' => 'Congo - Brazzaville', 'pt' => 'República do Congo']],
        'KP' => ['dial' => '850', 'flag' => '🇰🇵', 'names' => ['es' => 'Corea del Norte', 'en' => 'North Korea', 'pt' => 'Coreia do Norte']],
        'KR' => ['dial' => '82', 'flag' => '🇰🇷', 'names' => ['es' => 'Corea del Sur', 'en' => 'South Korea', 'pt' => 'Coreia do Sul']],
        'CR' => ['dial' => '506', 'flag' => '🇨🇷', 'names' => ['es' => 'Costa Rica', 'en' => 'Costa Rica', 'pt' => 'Costa Rica']],
        'CI' => ['dial' => '225', 'flag' => '🇨🇮', 'names' => ['es' => 'Côte d’Ivoire', 'en' => 'Côte d’Ivoire', 'pt' => 'Costa do Marfim']],
        'HR' => ['dial' => '385', 'flag' => '🇭🇷', 'names' => ['es' => 'Croacia', 'en' => 'Croatia', 'pt' => 'Croácia']],
        'CU' => ['dial' => '53', 'flag' => '🇨🇺', 'names' => ['es' => 'Cuba', 'en' => 'Cuba', 'pt' => 'Cuba']],
        'CW' => ['dial' => '599', 'flag' => '🇨🇼', 'names' => ['es' => 'Curazao', 'en' => 'Curaçao', 'pt' => 'Curaçao']],
        'DK' => ['dial' => '45', 'flag' => '🇩🇰', 'names' => ['es' => 'Dinamarca', 'en' => 'Denmark', 'pt' => 'Dinamarca']],
        'DM' => ['dial' => '1767', 'flag' => '🇩🇲', 'names' => ['es' => 'Dominica', 'en' => 'Dominica', 'pt' => 'Dominica']],
        'EC' => ['dial' => '593', 'flag' => '🇪🇨', 'names' => ['es' => 'Ecuador', 'en' => 'Ecuador', 'pt' => 'Equador']],
        'EG' => ['dial' => '20', 'flag' => '🇪🇬', 'names' => ['es' => 'Egipto', 'en' => 'Egypt', 'pt' => 'Egito']],
        'SV' => ['dial' => '503', 'flag' => '🇸🇻', 'names' => ['es' => 'El Salvador', 'en' => 'El Salvador', 'pt' => 'El Salvador']],
        'AE' => ['dial' => '971', 'flag' => '🇦🇪', 'names' => ['es' => 'Emiratos Árabes Unidos', 'en' => 'United Arab Emirates', 'pt' => 'Emirados Árabes Unidos']],
        'ER' => ['dial' => '291', 'flag' => '🇪🇷', 'names' => ['es' => 'Eritrea', 'en' => 'Eritrea', 'pt' => 'Eritreia']],
        'SK' => ['dial' => '421', 'flag' => '🇸🇰', 'names' => ['es' => 'Eslovaquia', 'en' => 'Slovakia', 'pt' => 'Eslováquia']],
        'SI' => ['dial' => '386', 'flag' => '🇸🇮', 'names' => ['es' => 'Eslovenia', 'en' => 'Slovenia', 'pt' => 'Eslovênia']],
        'ES' => ['dial' => '34', 'flag' => '🇪🇸', 'names' => ['es' => 'España', 'en' => 'Spain', 'pt' => 'Espanha']],
        'US' => ['dial' => '1', 'flag' => '🇺🇸', 'names' => ['es' => 'Estados Unidos', 'en' => 'United States', 'pt' => 'Estados Unidos']],
        'EE' => ['dial' => '372', 'flag' => '🇪🇪', 'names' => ['es' => 'Estonia', 'en' => 'Estonia', 'pt' => 'Estônia']],
        'SZ' => ['dial' => '268', 'flag' => '🇸🇿', 'names' => ['es' => 'Esuatini', 'en' => 'Eswatini', 'pt' => 'Essuatíni']],
        'ET' => ['dial' => '251', 'flag' => '🇪🇹', 'names' => ['es' => 'Etiopía', 'en' => 'Ethiopia', 'pt' => 'Etiópia']],
        'PH' => ['dial' => '63', 'flag' => '🇵🇭', 'names' => ['es' => 'Filipinas', 'en' => 'Philippines', 'pt' => 'Filipinas']],
        'FI' => ['dial' => '358', 'flag' => '🇫🇮', 'names' => ['es' => 'Finlandia', 'en' => 'Finland', 'pt' => 'Finlândia']],
        'FJ' => ['dial' => '679', 'flag' => '🇫🇯', 'names' => ['es' => 'Fiyi', 'en' => 'Fiji', 'pt' => 'Fiji']],
        'FR' => ['dial' => '33', 'flag' => '🇫🇷', 'names' => ['es' => 'Francia', 'en' => 'France', 'pt' => 'França']],
        'GA' => ['dial' => '241', 'flag' => '🇬🇦', 'names' => ['es' => 'Gabón', 'en' => 'Gabon', 'pt' => 'Gabão']],
        'GM' => ['dial' => '220', 'flag' => '🇬🇲', 'names' => ['es' => 'Gambia', 'en' => 'Gambia', 'pt' => 'Gâmbia']],
        'GE' => ['dial' => '995', 'flag' => '🇬🇪', 'names' => ['es' => 'Georgia', 'en' => 'Georgia', 'pt' => 'Geórgia']],
        'GH' => ['dial' => '233', 'flag' => '🇬🇭', 'names' => ['es' => 'Ghana', 'en' => 'Ghana', 'pt' => 'Gana']],
        'GI' => ['dial' => '350', 'flag' => '🇬🇮', 'names' => ['es' => 'Gibraltar', 'en' => 'Gibraltar', 'pt' => 'Gibraltar']],
        'GD' => ['dial' => '1473', 'flag' => '🇬🇩', 'names' => ['es' => 'Granada', 'en' => 'Grenada', 'pt' => 'Granada']],
        'GR' => ['dial' => '30', 'flag' => '🇬🇷', 'names' => ['es' => 'Grecia', 'en' => 'Greece', 'pt' => 'Grécia']],
        'GL' => ['dial' => '299', 'flag' => '🇬🇱', 'names' => ['es' => 'Groenlandia', 'en' => 'Greenland', 'pt' => 'Groenlândia']],
        'GP' => ['dial' => '590', 'flag' => '🇬🇵', 'names' => ['es' => 'Guadalupe', 'en' => 'Guadeloupe', 'pt' => 'Guadalupe']],
        'GU' => ['dial' => '1671', 'flag' => '🇬🇺', 'names' => ['es' => 'Guam', 'en' => 'Guam', 'pt' => 'Guam']],
        'GT' => ['dial' => '502', 'flag' => '🇬🇹', 'names' => ['es' => 'Guatemala', 'en' => 'Guatemala', 'pt' => 'Guatemala']],
        'GF' => ['dial' => '594', 'flag' => '🇬🇫', 'names' => ['es' => 'Guayana Francesa', 'en' => 'French Guiana', 'pt' => 'Guiana Francesa']],
        'GG' => ['dial' => '44', 'flag' => '🇬🇬', 'names' => ['es' => 'Guernesey', 'en' => 'Guernsey', 'pt' => 'Guernsey']],
        'GN' => ['dial' => '224', 'flag' => '🇬🇳', 'names' => ['es' => 'Guinea', 'en' => 'Guinea', 'pt' => 'Guiné']],
        'GQ' => ['dial' => '240', 'flag' => '🇬🇶', 'names' => ['es' => 'Guinea Ecuatorial', 'en' => 'Equatorial Guinea', 'pt' => 'Guiné Equatorial']],
        'GW' => ['dial' => '245', 'flag' => '🇬🇼', 'names' => ['es' => 'Guinea-Bisáu', 'en' => 'Guinea-Bissau', 'pt' => 'Guiné-Bissau']],
        'GY' => ['dial' => '592', 'flag' => '🇬🇾', 'names' => ['es' => 'Guyana', 'en' => 'Guyana', 'pt' => 'Guiana']],
        'HT' => ['dial' => '509', 'flag' => '🇭🇹', 'names' => ['es' => 'Haití', 'en' => 'Haiti', 'pt' => 'Haiti']],
        'HN' => ['dial' => '504', 'flag' => '🇭🇳', 'names' => ['es' => 'Honduras', 'en' => 'Honduras', 'pt' => 'Honduras']],
        'HU' => ['dial' => '36', 'flag' => '🇭🇺', 'names' => ['es' => 'Hungría', 'en' => 'Hungary', 'pt' => 'Hungria']],
        'IN' => ['dial' => '91', 'flag' => '🇮🇳', 'names' => ['es' => 'India', 'en' => 'India', 'pt' => 'Índia']],
        'ID' => ['dial' => '62', 'flag' => '🇮🇩', 'names' => ['es' => 'Indonesia', 'en' => 'Indonesia', 'pt' => 'Indonésia']],
        'IQ' => ['dial' => '964', 'flag' => '🇮🇶', 'names' => ['es' => 'Irak', 'en' => 'Iraq', 'pt' => 'Iraque']],
        'IR' => ['dial' => '98', 'flag' => '🇮🇷', 'names' => ['es' => 'Irán', 'en' => 'Iran', 'pt' => 'Irã']],
        'IE' => ['dial' => '353', 'flag' => '🇮🇪', 'names' => ['es' => 'Irlanda', 'en' => 'Ireland', 'pt' => 'Irlanda']],
        'IM' => ['dial' => '44', 'flag' => '🇮🇲', 'names' => ['es' => 'Isla de Man', 'en' => 'Isle of Man', 'pt' => 'Ilha de Man']],
        'CX' => ['dial' => '61', 'flag' => '🇨🇽', 'names' => ['es' => 'Isla de Navidad', 'en' => 'Christmas Island', 'pt' => 'Ilha Christmas']],
        'NF' => ['dial' => '672', 'flag' => '🇳🇫', 'names' => ['es' => 'Isla Norfolk', 'en' => 'Norfolk Island', 'pt' => 'Ilha Norfolk']],
        'IS' => ['dial' => '354', 'flag' => '🇮🇸', 'names' => ['es' => 'Islandia', 'en' => 'Iceland', 'pt' => 'Islândia']],
        'AX' => ['dial' => '358', 'flag' => '🇦🇽', 'names' => ['es' => 'Islas Aland', 'en' => 'Åland Islands', 'pt' => 'Ilhas Aland']],
        'KY' => ['dial' => '1345', 'flag' => '🇰🇾', 'names' => ['es' => 'Islas Caimán', 'en' => 'Cayman Islands', 'pt' => 'Ilhas Cayman']],
        'CC' => ['dial' => '61', 'flag' => '🇨🇨', 'names' => ['es' => 'Islas Cocos', 'en' => 'Cocos (Keeling) Islands', 'pt' => 'Ilhas Cocos (Keeling)']],
        'CK' => ['dial' => '682', 'flag' => '🇨🇰', 'names' => ['es' => 'Islas Cook', 'en' => 'Cook Islands', 'pt' => 'Ilhas Cook']],
        'FO' => ['dial' => '298', 'flag' => '🇫🇴', 'names' => ['es' => 'Islas Feroe', 'en' => 'Faroe Islands', 'pt' => 'Ilhas Faroé']],
        'FK' => ['dial' => '500', 'flag' => '🇫🇰', 'names' => ['es' => 'Islas Malvinas', 'en' => 'Falkland Islands', 'pt' => 'Ilhas Malvinas']],
        'MP' => ['dial' => '1670', 'flag' => '🇲🇵', 'names' => ['es' => 'Islas Marianas del Norte', 'en' => 'Northern Mariana Islands', 'pt' => 'Ilhas Marianas do Norte']],
        'MH' => ['dial' => '692', 'flag' => '🇲🇭', 'names' => ['es' => 'Islas Marshall', 'en' => 'Marshall Islands', 'pt' => 'Ilhas Marshall']],
        'SB' => ['dial' => '677', 'flag' => '🇸🇧', 'names' => ['es' => 'Islas Salomón', 'en' => 'Solomon Islands', 'pt' => 'Ilhas Salomão']],
        'TC' => ['dial' => '1649', 'flag' => '🇹🇨', 'names' => ['es' => 'Islas Turcas y Caicos', 'en' => 'Turks & Caicos Islands', 'pt' => 'Ilhas Turcas e Caicos']],
        'VG' => ['dial' => '1284', 'flag' => '🇻🇬', 'names' => ['es' => 'Islas Vírgenes Británicas', 'en' => 'British Virgin Islands', 'pt' => 'Ilhas Virgens Britânicas']],
        'VI' => ['dial' => '1340', 'flag' => '🇻🇮', 'names' => ['es' => 'Islas Vírgenes de EE. UU.', 'en' => 'U.S. Virgin Islands', 'pt' => 'Ilhas Virgens Americanas']],
        'IL' => ['dial' => '972', 'flag' => '🇮🇱', 'names' => ['es' => 'Israel', 'en' => 'Israel', 'pt' => 'Israel']],
        'IT' => ['dial' => '39', 'flag' => '🇮🇹', 'names' => ['es' => 'Italia', 'en' => 'Italy', 'pt' => 'Itália']],
        'JM' => ['dial' => '1876', 'flag' => '🇯🇲', 'names' => ['es' => 'Jamaica', 'en' => 'Jamaica', 'pt' => 'Jamaica']],
        'JP' => ['dial' => '81', 'flag' => '🇯🇵', 'names' => ['es' => 'Japón', 'en' => 'Japan', 'pt' => 'Japão']],
        'JE' => ['dial' => '44', 'flag' => '🇯🇪', 'names' => ['es' => 'Jersey', 'en' => 'Jersey', 'pt' => 'Jersey']],
        'JO' => ['dial' => '962', 'flag' => '🇯🇴', 'names' => ['es' => 'Jordania', 'en' => 'Jordan', 'pt' => 'Jordânia']],
        'KZ' => ['dial' => '7', 'flag' => '🇰🇿', 'names' => ['es' => 'Kazajistán', 'en' => 'Kazakhstan', 'pt' => 'Cazaquistão']],
        'KE' => ['dial' => '254', 'flag' => '🇰🇪', 'names' => ['es' => 'Kenia', 'en' => 'Kenya', 'pt' => 'Quênia']],
        'KG' => ['dial' => '996', 'flag' => '🇰🇬', 'names' => ['es' => 'Kirguistán', 'en' => 'Kyrgyzstan', 'pt' => 'Quirguistão']],
        'KI' => ['dial' => '686', 'flag' => '🇰🇮', 'names' => ['es' => 'Kiribati', 'en' => 'Kiribati', 'pt' => 'Quiribati']],
        'KW' => ['dial' => '965', 'flag' => '🇰🇼', 'names' => ['es' => 'Kuwait', 'en' => 'Kuwait', 'pt' => 'Kuwait']],
        'LA' => ['dial' => '856', 'flag' => '🇱🇦', 'names' => ['es' => 'Laos', 'en' => 'Laos', 'pt' => 'Laos']],
        'LS' => ['dial' => '266', 'flag' => '🇱🇸', 'names' => ['es' => 'Lesoto', 'en' => 'Lesotho', 'pt' => 'Lesoto']],
        'LV' => ['dial' => '371', 'flag' => '🇱🇻', 'names' => ['es' => 'Letonia', 'en' => 'Latvia', 'pt' => 'Letônia']],
        'LB' => ['dial' => '961', 'flag' => '🇱🇧', 'names' => ['es' => 'Líbano', 'en' => 'Lebanon', 'pt' => 'Líbano']],
        'LR' => ['dial' => '231', 'flag' => '🇱🇷', 'names' => ['es' => 'Liberia', 'en' => 'Liberia', 'pt' => 'Libéria']],
        'LY' => ['dial' => '218', 'flag' => '🇱🇾', 'names' => ['es' => 'Libia', 'en' => 'Libya', 'pt' => 'Líbia']],
        'LI' => ['dial' => '423', 'flag' => '🇱🇮', 'names' => ['es' => 'Liechtenstein', 'en' => 'Liechtenstein', 'pt' => 'Liechtenstein']],
        'LT' => ['dial' => '370', 'flag' => '🇱🇹', 'names' => ['es' => 'Lituania', 'en' => 'Lithuania', 'pt' => 'Lituânia']],
        'LU' => ['dial' => '352', 'flag' => '🇱🇺', 'names' => ['es' => 'Luxemburgo', 'en' => 'Luxembourg', 'pt' => 'Luxemburgo']],
        'MK' => ['dial' => '389', 'flag' => '🇲🇰', 'names' => ['es' => 'Macedonia del Norte', 'en' => 'North Macedonia', 'pt' => 'Macedônia do Norte']],
        'MG' => ['dial' => '261', 'flag' => '🇲🇬', 'names' => ['es' => 'Madagascar', 'en' => 'Madagascar', 'pt' => 'Madagascar']],
        'MY' => ['dial' => '60', 'flag' => '🇲🇾', 'names' => ['es' => 'Malasia', 'en' => 'Malaysia', 'pt' => 'Malásia']],
        'MW' => ['dial' => '265', 'flag' => '🇲🇼', 'names' => ['es' => 'Malaui', 'en' => 'Malawi', 'pt' => 'Malaui']],
        'MV' => ['dial' => '960', 'flag' => '🇲🇻', 'names' => ['es' => 'Maldivas', 'en' => 'Maldives', 'pt' => 'Maldivas']],
        'ML' => ['dial' => '223', 'flag' => '🇲🇱', 'names' => ['es' => 'Mali', 'en' => 'Mali', 'pt' => 'Mali']],
        'MT' => ['dial' => '356', 'flag' => '🇲🇹', 'names' => ['es' => 'Malta', 'en' => 'Malta', 'pt' => 'Malta']],
        'MA' => ['dial' => '212', 'flag' => '🇲🇦', 'names' => ['es' => 'Marruecos', 'en' => 'Morocco', 'pt' => 'Marrocos']],
        'MQ' => ['dial' => '596', 'flag' => '🇲🇶', 'names' => ['es' => 'Martinica', 'en' => 'Martinique', 'pt' => 'Martinica']],
        'MU' => ['dial' => '230', 'flag' => '🇲🇺', 'names' => ['es' => 'Mauricio', 'en' => 'Mauritius', 'pt' => 'Maurício']],
        'MR' => ['dial' => '222', 'flag' => '🇲🇷', 'names' => ['es' => 'Mauritania', 'en' => 'Mauritania', 'pt' => 'Mauritânia']],
        'YT' => ['dial' => '262', 'flag' => '🇾🇹', 'names' => ['es' => 'Mayotte', 'en' => 'Mayotte', 'pt' => 'Mayotte']],
        'MX' => ['dial' => '52', 'flag' => '🇲🇽', 'names' => ['es' => 'México', 'en' => 'Mexico', 'pt' => 'México']],
        'FM' => ['dial' => '691', 'flag' => '🇫🇲', 'names' => ['es' => 'Micronesia', 'en' => 'Micronesia', 'pt' => 'Micronésia']],
        'MD' => ['dial' => '373', 'flag' => '🇲🇩', 'names' => ['es' => 'Moldavia', 'en' => 'Moldova', 'pt' => 'Moldávia']],
        'MC' => ['dial' => '377', 'flag' => '🇲🇨', 'names' => ['es' => 'Mónaco', 'en' => 'Monaco', 'pt' => 'Mônaco']],
        'MN' => ['dial' => '976', 'flag' => '🇲🇳', 'names' => ['es' => 'Mongolia', 'en' => 'Mongolia', 'pt' => 'Mongólia']],
        'ME' => ['dial' => '382', 'flag' => '🇲🇪', 'names' => ['es' => 'Montenegro', 'en' => 'Montenegro', 'pt' => 'Montenegro']],
        'MS' => ['dial' => '1664', 'flag' => '🇲🇸', 'names' => ['es' => 'Montserrat', 'en' => 'Montserrat', 'pt' => 'Montserrat']],
        'MZ' => ['dial' => '258', 'flag' => '🇲🇿', 'names' => ['es' => 'Mozambique', 'en' => 'Mozambique', 'pt' => 'Moçambique']],
        'MM' => ['dial' => '95', 'flag' => '🇲🇲', 'names' => ['es' => 'Myanmar (Birmania)', 'en' => 'Myanmar (Burma)', 'pt' => 'Mianmar (Birmânia)']],
        'NA' => ['dial' => '264', 'flag' => '🇳🇦', 'names' => ['es' => 'Namibia', 'en' => 'Namibia', 'pt' => 'Namíbia']],
        'NR' => ['dial' => '674', 'flag' => '🇳🇷', 'names' => ['es' => 'Nauru', 'en' => 'Nauru', 'pt' => 'Nauru']],
        'NP' => ['dial' => '977', 'flag' => '🇳🇵', 'names' => ['es' => 'Nepal', 'en' => 'Nepal', 'pt' => 'Nepal']],
        'NI' => ['dial' => '505', 'flag' => '🇳🇮', 'names' => ['es' => 'Nicaragua', 'en' => 'Nicaragua', 'pt' => 'Nicarágua']],
        'NE' => ['dial' => '227', 'flag' => '🇳🇪', 'names' => ['es' => 'Níger', 'en' => 'Niger', 'pt' => 'Níger']],
        'NG' => ['dial' => '234', 'flag' => '🇳🇬', 'names' => ['es' => 'Nigeria', 'en' => 'Nigeria', 'pt' => 'Nigéria']],
        'NU' => ['dial' => '683', 'flag' => '🇳🇺', 'names' => ['es' => 'Niue', 'en' => 'Niue', 'pt' => 'Niue']],
        'NO' => ['dial' => '47', 'flag' => '🇳🇴', 'names' => ['es' => 'Noruega', 'en' => 'Norway', 'pt' => 'Noruega']],
        'NC' => ['dial' => '687', 'flag' => '🇳🇨', 'names' => ['es' => 'Nueva Caledonia', 'en' => 'New Caledonia', 'pt' => 'Nova Caledônia']],
        'NZ' => ['dial' => '64', 'flag' => '🇳🇿', 'names' => ['es' => 'Nueva Zelanda', 'en' => 'New Zealand', 'pt' => 'Nova Zelândia']],
        'OM' => ['dial' => '968', 'flag' => '🇴🇲', 'names' => ['es' => 'Omán', 'en' => 'Oman', 'pt' => 'Omã']],
        'NL' => ['dial' => '31', 'flag' => '🇳🇱', 'names' => ['es' => 'Países Bajos', 'en' => 'Netherlands', 'pt' => 'Países Baixos']],
        'PK' => ['dial' => '92', 'flag' => '🇵🇰', 'names' => ['es' => 'Pakistán', 'en' => 'Pakistan', 'pt' => 'Paquistão']],
        'PW' => ['dial' => '680', 'flag' => '🇵🇼', 'names' => ['es' => 'Palaos', 'en' => 'Palau', 'pt' => 'Palau']],
        'PA' => ['dial' => '507', 'flag' => '🇵🇦', 'names' => ['es' => 'Panamá', 'en' => 'Panama', 'pt' => 'Panamá']],
        'PG' => ['dial' => '675', 'flag' => '🇵🇬', 'names' => ['es' => 'Papúa Nueva Guinea', 'en' => 'Papua New Guinea', 'pt' => 'Papua-Nova Guiné']],
        'PY' => ['dial' => '595', 'flag' => '🇵🇾', 'names' => ['es' => 'Paraguay', 'en' => 'Paraguay', 'pt' => 'Paraguai']],
        'PE' => ['dial' => '51', 'flag' => '🇵🇪', 'names' => ['es' => 'Perú', 'en' => 'Peru', 'pt' => 'Peru']],
        'PF' => ['dial' => '689', 'flag' => '🇵🇫', 'names' => ['es' => 'Polinesia Francesa', 'en' => 'French Polynesia', 'pt' => 'Polinésia Francesa']],
        'PL' => ['dial' => '48', 'flag' => '🇵🇱', 'names' => ['es' => 'Polonia', 'en' => 'Poland', 'pt' => 'Polônia']],
        'PT' => ['dial' => '351', 'flag' => '🇵🇹', 'names' => ['es' => 'Portugal', 'en' => 'Portugal', 'pt' => 'Portugal']],
        'PR' => ['dial' => '1787', 'flag' => '🇵🇷', 'names' => ['es' => 'Puerto Rico', 'en' => 'Puerto Rico', 'pt' => 'Porto Rico']],
        'HK' => ['dial' => '852', 'flag' => '🇭🇰', 'names' => ['es' => 'RAE de Hong Kong (China)', 'en' => 'Hong Kong SAR China', 'pt' => 'Hong Kong, RAE da China']],
        'MO' => ['dial' => '853', 'flag' => '🇲🇴', 'names' => ['es' => 'RAE de Macao (China)', 'en' => 'Macao SAR China', 'pt' => 'Macau, RAE da China']],
        'GB' => ['dial' => '44', 'flag' => '🇬🇧', 'names' => ['es' => 'Reino Unido', 'en' => 'United Kingdom', 'pt' => 'Reino Unido']],
        'CF' => ['dial' => '236', 'flag' => '🇨🇫', 'names' => ['es' => 'República Centroafricana', 'en' => 'Central African Republic', 'pt' => 'República Centro-Africana']],
        'CD' => ['dial' => '243', 'flag' => '🇨🇩', 'names' => ['es' => 'República Democrática del Congo', 'en' => 'Congo - Kinshasa', 'pt' => 'Congo - Kinshasa']],
        'DO' => ['dial' => '1809', 'flag' => '🇩🇴', 'names' => ['es' => 'República Dominicana', 'en' => 'Dominican Republic', 'pt' => 'República Dominicana']],
        'RE' => ['dial' => '262', 'flag' => '🇷🇪', 'names' => ['es' => 'Reunión', 'en' => 'Réunion', 'pt' => 'Reunião']],
        'RW' => ['dial' => '250', 'flag' => '🇷🇼', 'names' => ['es' => 'Ruanda', 'en' => 'Rwanda', 'pt' => 'Ruanda']],
        'RO' => ['dial' => '40', 'flag' => '🇷🇴', 'names' => ['es' => 'Rumanía', 'en' => 'Romania', 'pt' => 'Romênia']],
        'RU' => ['dial' => '7', 'flag' => '🇷🇺', 'names' => ['es' => 'Rusia', 'en' => 'Russia', 'pt' => 'Rússia']],
        'EH' => ['dial' => '212', 'flag' => '🇪🇭', 'names' => ['es' => 'Sáhara Occidental', 'en' => 'Western Sahara', 'pt' => 'Saara Ocidental']],
        'WS' => ['dial' => '685', 'flag' => '🇼🇸', 'names' => ['es' => 'Samoa', 'en' => 'Samoa', 'pt' => 'Samoa']],
        'AS' => ['dial' => '1684', 'flag' => '🇦🇸', 'names' => ['es' => 'Samoa Americana', 'en' => 'American Samoa', 'pt' => 'Samoa Americana']],
        'BL' => ['dial' => '590', 'flag' => '🇧🇱', 'names' => ['es' => 'San Bartolomé', 'en' => 'St. Barthélemy', 'pt' => 'São Bartolomeu']],
        'KN' => ['dial' => '1869', 'flag' => '🇰🇳', 'names' => ['es' => 'San Cristóbal y Nieves', 'en' => 'St. Kitts & Nevis', 'pt' => 'São Cristóvão e Névis']],
        'SM' => ['dial' => '378', 'flag' => '🇸🇲', 'names' => ['es' => 'San Marino', 'en' => 'San Marino', 'pt' => 'San Marino']],
        'MF' => ['dial' => '590', 'flag' => '🇲🇫', 'names' => ['es' => 'San Martín', 'en' => 'St. Martin', 'pt' => 'São Martinho']],
        'PM' => ['dial' => '508', 'flag' => '🇵🇲', 'names' => ['es' => 'San Pedro y Miquelón', 'en' => 'St. Pierre & Miquelon', 'pt' => 'São Pedro e Miquelão']],
        'VC' => ['dial' => '1784', 'flag' => '🇻🇨', 'names' => ['es' => 'San Vicente y las Granadinas', 'en' => 'St. Vincent & Grenadines', 'pt' => 'São Vicente e Granadinas']],
        'SH' => ['dial' => '290', 'flag' => '🇸🇭', 'names' => ['es' => 'Santa Elena', 'en' => 'St. Helena', 'pt' => 'Santa Helena']],
        'LC' => ['dial' => '1758', 'flag' => '🇱🇨', 'names' => ['es' => 'Santa Lucía', 'en' => 'St. Lucia', 'pt' => 'Santa Lúcia']],
        'ST' => ['dial' => '239', 'flag' => '🇸🇹', 'names' => ['es' => 'Santo Tomé y Príncipe', 'en' => 'São Tomé & Príncipe', 'pt' => 'São Tomé e Príncipe']],
        'SN' => ['dial' => '221', 'flag' => '🇸🇳', 'names' => ['es' => 'Senegal', 'en' => 'Senegal', 'pt' => 'Senegal']],
        'RS' => ['dial' => '381', 'flag' => '🇷🇸', 'names' => ['es' => 'Serbia', 'en' => 'Serbia', 'pt' => 'Sérvia']],
        'SC' => ['dial' => '248', 'flag' => '🇸🇨', 'names' => ['es' => 'Seychelles', 'en' => 'Seychelles', 'pt' => 'Seicheles']],
        'SL' => ['dial' => '232', 'flag' => '🇸🇱', 'names' => ['es' => 'Sierra Leona', 'en' => 'Sierra Leone', 'pt' => 'Serra Leoa']],
        'SG' => ['dial' => '65', 'flag' => '🇸🇬', 'names' => ['es' => 'Singapur', 'en' => 'Singapore', 'pt' => 'Singapura']],
        'SX' => ['dial' => '1721', 'flag' => '🇸🇽', 'names' => ['es' => 'Sint Maarten', 'en' => 'Sint Maarten', 'pt' => 'Sint Maarten']],
        'SY' => ['dial' => '963', 'flag' => '🇸🇾', 'names' => ['es' => 'Siria', 'en' => 'Syria', 'pt' => 'Síria']],
        'SO' => ['dial' => '252', 'flag' => '🇸🇴', 'names' => ['es' => 'Somalia', 'en' => 'Somalia', 'pt' => 'Somália']],
        'LK' => ['dial' => '94', 'flag' => '🇱🇰', 'names' => ['es' => 'Sri Lanka', 'en' => 'Sri Lanka', 'pt' => 'Sri Lanka']],
        'ZA' => ['dial' => '27', 'flag' => '🇿🇦', 'names' => ['es' => 'Sudáfrica', 'en' => 'South Africa', 'pt' => 'África do Sul']],
        'SD' => ['dial' => '249', 'flag' => '🇸🇩', 'names' => ['es' => 'Sudán', 'en' => 'Sudan', 'pt' => 'Sudão']],
        'SS' => ['dial' => '211', 'flag' => '🇸🇸', 'names' => ['es' => 'Sudán del Sur', 'en' => 'South Sudan', 'pt' => 'Sudão do Sul']],
        'SE' => ['dial' => '46', 'flag' => '🇸🇪', 'names' => ['es' => 'Suecia', 'en' => 'Sweden', 'pt' => 'Suécia']],
        'CH' => ['dial' => '41', 'flag' => '🇨🇭', 'names' => ['es' => 'Suiza', 'en' => 'Switzerland', 'pt' => 'Suíça']],
        'SR' => ['dial' => '597', 'flag' => '🇸🇷', 'names' => ['es' => 'Surinam', 'en' => 'Suriname', 'pt' => 'Suriname']],
        'SJ' => ['dial' => '47', 'flag' => '🇸🇯', 'names' => ['es' => 'Svalbard y Jan Mayen', 'en' => 'Svalbard & Jan Mayen', 'pt' => 'Svalbard e Jan Mayen']],
        'TH' => ['dial' => '66', 'flag' => '🇹🇭', 'names' => ['es' => 'Tailandia', 'en' => 'Thailand', 'pt' => 'Tailândia']],
        'TW' => ['dial' => '886', 'flag' => '🇹🇼', 'names' => ['es' => 'Taiwán', 'en' => 'Taiwan', 'pt' => 'Taiwan']],
        'TZ' => ['dial' => '255', 'flag' => '🇹🇿', 'names' => ['es' => 'Tanzania', 'en' => 'Tanzania', 'pt' => 'Tanzânia']],
        'TJ' => ['dial' => '992', 'flag' => '🇹🇯', 'names' => ['es' => 'Tayikistán', 'en' => 'Tajikistan', 'pt' => 'Tadjiquistão']],
        'IO' => ['dial' => '246', 'flag' => '🇮🇴', 'names' => ['es' => 'Territorio Británico del Océano Índico', 'en' => 'British Indian Ocean Territory', 'pt' => 'Território Britânico do Oceano Índico']],
        'PS' => ['dial' => '970', 'flag' => '🇵🇸', 'names' => ['es' => 'Territorios Palestinos', 'en' => 'Palestinian Territories', 'pt' => 'Territórios palestinos']],
        'TL' => ['dial' => '670', 'flag' => '🇹🇱', 'names' => ['es' => 'Timor-Leste', 'en' => 'Timor-Leste', 'pt' => 'Timor-Leste']],
        'TG' => ['dial' => '228', 'flag' => '🇹🇬', 'names' => ['es' => 'Togo', 'en' => 'Togo', 'pt' => 'Togo']],
        'TK' => ['dial' => '690', 'flag' => '🇹🇰', 'names' => ['es' => 'Tokelau', 'en' => 'Tokelau', 'pt' => 'Tokelau']],
        'TO' => ['dial' => '676', 'flag' => '🇹🇴', 'names' => ['es' => 'Tonga', 'en' => 'Tonga', 'pt' => 'Tonga']],
        'TT' => ['dial' => '1868', 'flag' => '🇹🇹', 'names' => ['es' => 'Trinidad y Tobago', 'en' => 'Trinidad & Tobago', 'pt' => 'Trinidad e Tobago']],
        'TN' => ['dial' => '216', 'flag' => '🇹🇳', 'names' => ['es' => 'Túnez', 'en' => 'Tunisia', 'pt' => 'Tunísia']],
        'TM' => ['dial' => '993', 'flag' => '🇹🇲', 'names' => ['es' => 'Turkmenistán', 'en' => 'Turkmenistan', 'pt' => 'Turcomenistão']],
        'TR' => ['dial' => '90', 'flag' => '🇹🇷', 'names' => ['es' => 'Turquía', 'en' => 'Turkey', 'pt' => 'Turquia']],
        'TV' => ['dial' => '688', 'flag' => '🇹🇻', 'names' => ['es' => 'Tuvalu', 'en' => 'Tuvalu', 'pt' => 'Tuvalu']],
        'UA' => ['dial' => '380', 'flag' => '🇺🇦', 'names' => ['es' => 'Ucrania', 'en' => 'Ukraine', 'pt' => 'Ucrânia']],
        'UG' => ['dial' => '256', 'flag' => '🇺🇬', 'names' => ['es' => 'Uganda', 'en' => 'Uganda', 'pt' => 'Uganda']],
        'UY' => ['dial' => '598', 'flag' => '🇺🇾', 'names' => ['es' => 'Uruguay', 'en' => 'Uruguay', 'pt' => 'Uruguai']],
        'UZ' => ['dial' => '998', 'flag' => '🇺🇿', 'names' => ['es' => 'Uzbekistán', 'en' => 'Uzbekistan', 'pt' => 'Uzbequistão']],
        'VU' => ['dial' => '678', 'flag' => '🇻🇺', 'names' => ['es' => 'Vanuatu', 'en' => 'Vanuatu', 'pt' => 'Vanuatu']],
        'VE' => ['dial' => '58', 'flag' => '🇻🇪', 'names' => ['es' => 'Venezuela', 'en' => 'Venezuela', 'pt' => 'Venezuela']],
        'VN' => ['dial' => '84', 'flag' => '🇻🇳', 'names' => ['es' => 'Vietnam', 'en' => 'Vietnam', 'pt' => 'Vietnã']],
        'WF' => ['dial' => '681', 'flag' => '🇼🇫', 'names' => ['es' => 'Wallis y Futuna', 'en' => 'Wallis & Futuna', 'pt' => 'Wallis e Futuna']],
        'YE' => ['dial' => '967', 'flag' => '🇾🇪', 'names' => ['es' => 'Yemen', 'en' => 'Yemen', 'pt' => 'Iêmen']],
        'DJ' => ['dial' => '253', 'flag' => '🇩🇯', 'names' => ['es' => 'Yibuti', 'en' => 'Djibouti', 'pt' => 'Djibuti']],
        'ZM' => ['dial' => '260', 'flag' => '🇿🇲', 'names' => ['es' => 'Zambia', 'en' => 'Zambia', 'pt' => 'Zâmbia']],
        'ZW' => ['dial' => '263', 'flag' => '🇿🇼', 'names' => ['es' => 'Zimbabue', 'en' => 'Zimbabwe', 'pt' => 'Zimbábue']],
    ],

];
